/**
 * L3vels Api
 * L3vels API for Game developers
 *
 * The version of the OpenAPI document: 0.3
 * Contact: support@l3vels.xyz
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.5.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * TransactionApi.h
 *
 * 
 */

#ifndef API_TransactionApi_H_
#define API_TransactionApi_H_



#include "CppRestOpenAPIClient/ApiClient.h"

#include "CppRestOpenAPIClient/model/Transaction.h"
#include <cpprest/details/basic_types.h>
#include <boost/optional.hpp>

namespace api {

using namespace models;



class  TransactionApi 
{
public:

    explicit TransactionApi( std::shared_ptr<const ApiClient> apiClient );

    virtual ~TransactionApi();

    /// <summary>
    /// Retrieve Transaction by ID
    /// </summary>
    /// <remarks>
    /// Retrieve transaction by ID
    /// </remarks>
    /// <param name="authorization">API key is associated with multiple projects. Please include it in to use developers API.</param>
    /// <param name="id"></param>
    /// <param name="projectId"></param>
    pplx::task<std::shared_ptr<Transaction>> transactionControllerTransactionById(
        utility::string_t authorization,
        utility::string_t id,
        utility::string_t projectId
    ) const;
    /// <summary>
    /// Retrieve transactions
    /// </summary>
    /// <remarks>
    /// Retrieve all transactions.
    /// </remarks>
    /// <param name="authorization">API key is associated with multiple projects. Please include it in to use developers API.</param>
    /// <param name="projectId">Game/project ID to find transactions in your game. Example: Fortnite, Minecraft, etc.</param>
    /// <param name="collectionId">Filter transactions by collection. Example: Get transactions only from Weapons collection. (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="playerId">Player ID to mint to. You can provide player ID or player address (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="sort">Asset field to sort by. You can sort by name, created_on and etc. (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="order">Sort order (ASC for ascending or DESC for descending) (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="searchText">Search transactions by name (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="limit">Number of transactions to return per page (optional, default to 0.0)</param>
    /// <param name="page">Page number (optional, default to 0.0)</param>
    pplx::task<std::shared_ptr<Transaction>> transactionControllerTransactions(
        utility::string_t authorization,
        utility::string_t projectId,
        boost::optional<utility::string_t> collectionId,
        boost::optional<utility::string_t> playerId,
        boost::optional<utility::string_t> sort,
        boost::optional<utility::string_t> order,
        boost::optional<utility::string_t> searchText,
        boost::optional<double> limit,
        boost::optional<double> page
    ) const;
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="authorization">API key is associated with multiple projects. Please include it in to use developers API.</param>
    pplx::task<void> transactionControllerWebhook(
        utility::string_t authorization
    ) const;

protected:
    std::shared_ptr<const ApiClient> m_ApiClient;
};

}

#endif /* API_TransactionApi_H_ */

