/**
 * L3vels Api
 * L3vels API for Game developers
 *
 * The version of the OpenAPI document: 0.3
 * Contact: support@l3vels.xyz
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.5.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/CreatePlayerDto.h"

namespace models {



CreatePlayerDto::CreatePlayerDto()
{
    m_Unique_id = utility::conversions::to_string_t("");
    m_Unique_idIsSet = false;
    m_Name = utility::conversions::to_string_t("");
    m_NameIsSet = false;
    m_Username = utility::conversions::to_string_t("");
    m_UsernameIsSet = false;
    m_Email = utility::conversions::to_string_t("");
    m_EmailIsSet = false;
    m_Avatar = utility::conversions::to_string_t("");
    m_AvatarIsSet = false;
    m_Project_id = utility::conversions::to_string_t("");
    m_Project_idIsSet = false;
    m_Is_create_wallet = false;
    m_Is_create_walletIsSet = false;
    m_Custom_propsIsSet = false;
}

CreatePlayerDto::~CreatePlayerDto()
{
}

void CreatePlayerDto::validate()
{
    // TODO: implement validation
}

web::json::value CreatePlayerDto::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_Unique_idIsSet)
    {
        val[utility::conversions::to_string_t(U("unique_id"))] = ModelBase::toJson(m_Unique_id);
    }
    if(m_NameIsSet)
    {
        val[utility::conversions::to_string_t(U("name"))] = ModelBase::toJson(m_Name);
    }
    if(m_UsernameIsSet)
    {
        val[utility::conversions::to_string_t(U("username"))] = ModelBase::toJson(m_Username);
    }
    if(m_EmailIsSet)
    {
        val[utility::conversions::to_string_t(U("email"))] = ModelBase::toJson(m_Email);
    }
    if(m_AvatarIsSet)
    {
        val[utility::conversions::to_string_t(U("avatar"))] = ModelBase::toJson(m_Avatar);
    }
    if(m_Project_idIsSet)
    {
        val[utility::conversions::to_string_t(U("project_id"))] = ModelBase::toJson(m_Project_id);
    }
    if(m_Is_create_walletIsSet)
    {
        val[utility::conversions::to_string_t(U("is_create_wallet"))] = ModelBase::toJson(m_Is_create_wallet);
    }
    if(m_Custom_propsIsSet)
    {
        val[utility::conversions::to_string_t(U("custom_props"))] = ModelBase::toJson(m_Custom_props);
    }

    return val;
}

bool CreatePlayerDto::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("unique_id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("unique_id")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setUniqueId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setUniqueId);
            setUniqueId(refVal_setUniqueId);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("name"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("name")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setName);
            setName(refVal_setName);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("username"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("username")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setUsername;
            ok &= ModelBase::fromJson(fieldValue, refVal_setUsername);
            setUsername(refVal_setUsername);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("email"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("email")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setEmail;
            ok &= ModelBase::fromJson(fieldValue, refVal_setEmail);
            setEmail(refVal_setEmail);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("avatar"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("avatar")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setAvatar;
            ok &= ModelBase::fromJson(fieldValue, refVal_setAvatar);
            setAvatar(refVal_setAvatar);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("project_id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("project_id")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setProjectId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setProjectId);
            setProjectId(refVal_setProjectId);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("is_create_wallet"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("is_create_wallet")));
        if(!fieldValue.is_null())
        {
            bool refVal_setIsCreateWallet;
            ok &= ModelBase::fromJson(fieldValue, refVal_setIsCreateWallet);
            setIsCreateWallet(refVal_setIsCreateWallet);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("custom_props"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("custom_props")));
        if(!fieldValue.is_null())
        {
            std::vector<utility::string_t> refVal_setCustomProps;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCustomProps);
            setCustomProps(refVal_setCustomProps);
        }
    }
    return ok;
}

void CreatePlayerDto::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_Unique_idIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("unique_id")), m_Unique_id));
    }
    if(m_NameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("name")), m_Name));
    }
    if(m_UsernameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("username")), m_Username));
    }
    if(m_EmailIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("email")), m_Email));
    }
    if(m_AvatarIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("avatar")), m_Avatar));
    }
    if(m_Project_idIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("project_id")), m_Project_id));
    }
    if(m_Is_create_walletIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("is_create_wallet")), m_Is_create_wallet));
    }
    if(m_Custom_propsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("custom_props")), m_Custom_props));
    }
}

bool CreatePlayerDto::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("unique_id"))))
    {
        utility::string_t refVal_setUniqueId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("unique_id"))), refVal_setUniqueId );
        setUniqueId(refVal_setUniqueId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("name"))))
    {
        utility::string_t refVal_setName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("name"))), refVal_setName );
        setName(refVal_setName);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("username"))))
    {
        utility::string_t refVal_setUsername;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("username"))), refVal_setUsername );
        setUsername(refVal_setUsername);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("email"))))
    {
        utility::string_t refVal_setEmail;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("email"))), refVal_setEmail );
        setEmail(refVal_setEmail);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("avatar"))))
    {
        utility::string_t refVal_setAvatar;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("avatar"))), refVal_setAvatar );
        setAvatar(refVal_setAvatar);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("project_id"))))
    {
        utility::string_t refVal_setProjectId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("project_id"))), refVal_setProjectId );
        setProjectId(refVal_setProjectId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("is_create_wallet"))))
    {
        bool refVal_setIsCreateWallet;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("is_create_wallet"))), refVal_setIsCreateWallet );
        setIsCreateWallet(refVal_setIsCreateWallet);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("custom_props"))))
    {
        std::vector<utility::string_t> refVal_setCustomProps;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("custom_props"))), refVal_setCustomProps );
        setCustomProps(refVal_setCustomProps);
    }
    return ok;
}

utility::string_t CreatePlayerDto::getUniqueId() const
{
    return m_Unique_id;
}

void CreatePlayerDto::setUniqueId(const utility::string_t& value)
{
    m_Unique_id = value;
    m_Unique_idIsSet = true;
}

bool CreatePlayerDto::uniqueIdIsSet() const
{
    return m_Unique_idIsSet;
}

void CreatePlayerDto::unsetUnique_id()
{
    m_Unique_idIsSet = false;
}
utility::string_t CreatePlayerDto::getName() const
{
    return m_Name;
}

void CreatePlayerDto::setName(const utility::string_t& value)
{
    m_Name = value;
    m_NameIsSet = true;
}

bool CreatePlayerDto::nameIsSet() const
{
    return m_NameIsSet;
}

void CreatePlayerDto::unsetName()
{
    m_NameIsSet = false;
}
utility::string_t CreatePlayerDto::getUsername() const
{
    return m_Username;
}

void CreatePlayerDto::setUsername(const utility::string_t& value)
{
    m_Username = value;
    m_UsernameIsSet = true;
}

bool CreatePlayerDto::usernameIsSet() const
{
    return m_UsernameIsSet;
}

void CreatePlayerDto::unsetUsername()
{
    m_UsernameIsSet = false;
}
utility::string_t CreatePlayerDto::getEmail() const
{
    return m_Email;
}

void CreatePlayerDto::setEmail(const utility::string_t& value)
{
    m_Email = value;
    m_EmailIsSet = true;
}

bool CreatePlayerDto::emailIsSet() const
{
    return m_EmailIsSet;
}

void CreatePlayerDto::unsetEmail()
{
    m_EmailIsSet = false;
}
utility::string_t CreatePlayerDto::getAvatar() const
{
    return m_Avatar;
}

void CreatePlayerDto::setAvatar(const utility::string_t& value)
{
    m_Avatar = value;
    m_AvatarIsSet = true;
}

bool CreatePlayerDto::avatarIsSet() const
{
    return m_AvatarIsSet;
}

void CreatePlayerDto::unsetAvatar()
{
    m_AvatarIsSet = false;
}
utility::string_t CreatePlayerDto::getProjectId() const
{
    return m_Project_id;
}

void CreatePlayerDto::setProjectId(const utility::string_t& value)
{
    m_Project_id = value;
    m_Project_idIsSet = true;
}

bool CreatePlayerDto::projectIdIsSet() const
{
    return m_Project_idIsSet;
}

void CreatePlayerDto::unsetProject_id()
{
    m_Project_idIsSet = false;
}
bool CreatePlayerDto::isIsCreateWallet() const
{
    return m_Is_create_wallet;
}

void CreatePlayerDto::setIsCreateWallet(bool value)
{
    m_Is_create_wallet = value;
    m_Is_create_walletIsSet = true;
}

bool CreatePlayerDto::isCreateWalletIsSet() const
{
    return m_Is_create_walletIsSet;
}

void CreatePlayerDto::unsetIs_create_wallet()
{
    m_Is_create_walletIsSet = false;
}
std::vector<utility::string_t>& CreatePlayerDto::getCustomProps()
{
    return m_Custom_props;
}

void CreatePlayerDto::setCustomProps(const std::vector<utility::string_t>& value)
{
    m_Custom_props = value;
    m_Custom_propsIsSet = true;
}

bool CreatePlayerDto::customPropsIsSet() const
{
    return m_Custom_propsIsSet;
}

void CreatePlayerDto::unsetCustom_props()
{
    m_Custom_propsIsSet = false;
}
}


