/**
 * L3vels Api
 * L3vels API for Game developers
 *
 * The version of the OpenAPI document: 0.3
 * Contact: support@l3vels.xyz
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.5.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOpenAPIClient/model/SetContractUriDto.h"

namespace models {



SetContractUriDto::SetContractUriDto()
{
    m_Project_id = utility::conversions::to_string_t("");
    m_Project_idIsSet = false;
    m_Collection_id = utility::conversions::to_string_t("");
    m_Collection_idIsSet = false;
    m_Contract_uri = utility::conversions::to_string_t("");
    m_Contract_uriIsSet = false;
}

SetContractUriDto::~SetContractUriDto()
{
}

void SetContractUriDto::validate()
{
    // TODO: implement validation
}

web::json::value SetContractUriDto::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_Project_idIsSet)
    {
        val[utility::conversions::to_string_t(U("project_id"))] = ModelBase::toJson(m_Project_id);
    }
    if(m_Collection_idIsSet)
    {
        val[utility::conversions::to_string_t(U("collection_id"))] = ModelBase::toJson(m_Collection_id);
    }
    if(m_Contract_uriIsSet)
    {
        val[utility::conversions::to_string_t(U("contract_uri"))] = ModelBase::toJson(m_Contract_uri);
    }

    return val;
}

bool SetContractUriDto::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("project_id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("project_id")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setProjectId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setProjectId);
            setProjectId(refVal_setProjectId);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("collection_id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("collection_id")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setCollectionId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCollectionId);
            setCollectionId(refVal_setCollectionId);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("contract_uri"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("contract_uri")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setContractUri;
            ok &= ModelBase::fromJson(fieldValue, refVal_setContractUri);
            setContractUri(refVal_setContractUri);
        }
    }
    return ok;
}

void SetContractUriDto::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_Project_idIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("project_id")), m_Project_id));
    }
    if(m_Collection_idIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("collection_id")), m_Collection_id));
    }
    if(m_Contract_uriIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("contract_uri")), m_Contract_uri));
    }
}

bool SetContractUriDto::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("project_id"))))
    {
        utility::string_t refVal_setProjectId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("project_id"))), refVal_setProjectId );
        setProjectId(refVal_setProjectId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("collection_id"))))
    {
        utility::string_t refVal_setCollectionId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("collection_id"))), refVal_setCollectionId );
        setCollectionId(refVal_setCollectionId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("contract_uri"))))
    {
        utility::string_t refVal_setContractUri;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("contract_uri"))), refVal_setContractUri );
        setContractUri(refVal_setContractUri);
    }
    return ok;
}

utility::string_t SetContractUriDto::getProjectId() const
{
    return m_Project_id;
}

void SetContractUriDto::setProjectId(const utility::string_t& value)
{
    m_Project_id = value;
    m_Project_idIsSet = true;
}

bool SetContractUriDto::projectIdIsSet() const
{
    return m_Project_idIsSet;
}

void SetContractUriDto::unsetProject_id()
{
    m_Project_idIsSet = false;
}
utility::string_t SetContractUriDto::getCollectionId() const
{
    return m_Collection_id;
}

void SetContractUriDto::setCollectionId(const utility::string_t& value)
{
    m_Collection_id = value;
    m_Collection_idIsSet = true;
}

bool SetContractUriDto::collectionIdIsSet() const
{
    return m_Collection_idIsSet;
}

void SetContractUriDto::unsetCollection_id()
{
    m_Collection_idIsSet = false;
}
utility::string_t SetContractUriDto::getContractUri() const
{
    return m_Contract_uri;
}

void SetContractUriDto::setContractUri(const utility::string_t& value)
{
    m_Contract_uri = value;
    m_Contract_uriIsSet = true;
}

bool SetContractUriDto::contractUriIsSet() const
{
    return m_Contract_uriIsSet;
}

void SetContractUriDto::unsetContract_uri()
{
    m_Contract_uriIsSet = false;
}
}


